#!/bin/bash

die () {
        local ret=$1; 
        local warning="$2"; shift 2
        warn "${warning:-Unknown error}" "$@"
        quit ${ret:-1}
}

warn () {
        local message="$1"; shift
        printf "$message" "$@" 1>&2
}

quit () {
        exit ${1:-0}
}

msg  () {
        local message="$1"
        shift
        printf "$message" $@
}

# Expects pkgname-pkgver-pkgrel string and returns pkgname
get_pkgname_from_string () {
        local pkgstring=$1
        pkgname=$(echo $pkgstring | sed 's/-[^-]+-[0-9.]+$//')
        if [ -n "$pkgname" ]; then
                echo $pkgname
                return 0
        fi
        return 1
}

# Expects pkgname-pkgver-pkgrel string and returns pkgver-pkgrel
get_pkgver_from_string () {
        local pkgstring=$1
        pkgver=$(echo $pkgstring | sed 's/.*\(-[^-]+-[0-9.]+\)$/\1/')
        if [ -n "$pkgver" ]; then
                echo $pkgver
                return 0
        fi
        return 1
}

# vim: set ts=8 et:
